### ISSUE TITLE
KoBoForm offline - java applets not working Firefox

### ISSUE THREAD

**Issue by Dylan-Gillespie** [kobotoolbox/koboform#123]
_From [tino.kre...@gmail.com](https://code.google.com/u/116906236256509083619/) on September 22, 2013 17:50:26_

What steps will reproduce the problem? 1. Download the offline version from https://code.google.com/p/kobo/downloads/detail?name=Kobo-win-1.0.22.exe and install it.
2. Run the program, either from the applications menu or by opening the html file directly in FF
3. Click on Menu, then Open from File What is the expected output? What do you see instead? Java applet doesn't open to select file from file system. Instead, small box opens with just the Load Form from File label and the close button.

_Original issue: http://code.google.com/p/kobo/issues/detail?id=121_

**Comment by Dylan-Gillespie** [comment]
_From [john.eth...@gmail.com](https://code.google.com/u/107202388567376291706/) on September 22, 2013 21:49:34_

I believe this to be a known issue with FireFox and Java 7 >: http://www.java.com/en/download/help/firefox_java.xml

**Comment by Dylan-Gillespie** [comment]
_From [tino.kre...@gmail.com](https://code.google.com/u/116906236256509083619/) on September 22, 2013 21:54:06_

I'm having this issue with Java 1.6_33 though..

**Comment by Dylan-Gillespie** [comment]
_From [apollo...@hotmail.com](https://code.google.com/u/113070400024749348403/) on October 04, 2013 09:52:18_

I looked at this and if I click the white area next to the close button, I get a popup  asking if I wanted to run Java from the app the first time, and then the file select screen opens. It opens automatically after more attempts at clicking on the open a file. I feel like the box is pretty small for this, just have no idea where to change it.

**Status:** Started

**Comment by tinok** [comment]
This seems to work now, using Firefox 24.0 and Java 1_6_33. Marking as closed.
