### ISSUE TITLE
Drag-n-drop destination ambivalent/defect - KoBoForms

### ISSUE THREAD

**Issue by Dylan-Gillespie** [kobotoolbox/koboform#43]
_From [tino.kre...@gmail.com](https://code.google.com/u/116906236256509083619/) on July 15, 2012 08:34:46_

Try dragging a question AFTER another question that has multiple response options but is collapsed (not showing the responses). 

KF will always show two lines in the GUI between the two questions where the third is supposed to be dropped. When dragging onto the lower dashed line, it works as intended. When dragging onto the higher dashed line, KF will drop the question above the first, rather than below the first question.

_Original issue: http://code.google.com/p/kobo/issues/detail?id=43_

**Comment by Dylan-Gillespie** [comment]
_From [tino.kre...@gmail.com](https://code.google.com/u/116906236256509083619/) on July 17, 2012 05:46:26_

This actually happens when dragging questions anywhere - except when dragging it behind multi or single select questions.

**Summary:** Drag-n-drop function defect - KoBoForms

**Comment by Dylan-Gillespie** [comment]
_From [tino.kre...@gmail.com](https://code.google.com/u/116906236256509083619/) on July 17, 2012 05:50:55_

**Summary:** Drag-n-drop destination ambivalent/defect - KoBoForms

**Comment by tinok** [comment]
Replaced by issue #106
