### ISSUE TITLE
Hand Coding custom skip logic

### ISSUE THREAD

**Issue by Dylan-Gillespie** [kobotoolbox/koboform#81]
Summary:
In places where someone has added custom skip logic, loading it into KoBoForm can break it. Also, there is no way to add skip logic that doesn't conform to the limited conditions KoBoForm can write. 
To be able to add Regex and complex conditions, there should be the option to write your skip logic in a text box. 
When loading unrecognized skip logic, KoBoForm should not change it, but load it into the box. 

proposed use-case:

Add to the usual condition UI, and then a check box in the corner that says, "hand code" and you click that you and just get a text box, and when there are things we don't support it'll just automatically revert to that.
 I guess if they uncheck "hand code" we'll need some "warning if you uncheck this you'll lose the work you have in your hand coded text area" warning too.

additional comments:
My concern is that we'll end up dumping bad code into the hand coding box instead of fixing it.

**Comment by tinok** [comment]
Duplicate with issue #82
